#!/bin/bash

if [ $EUID -eq 0 ]; then
	echo "Do not run this script as root. It will ask for credentials when needed."
	exit 1
fi


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
SCRIPT_DIR=$SCRIPT_DIR/Ubuntu

cp $SCRIPT_DIR/.bash_aliases ~
sudo cp $SCRIPT_DIR/release /usr/bin
source ~/.bash_aliases


if [ -d "$WORKSPACE/docker-recipes" ]; then
	echo "It seems this script has been run before. Exiting the installer..."
	exit 2
fi

mkdir -p $WORKSPACE

sudo apt update

sudo apt install -y xclip xmllint jq python3-dev python3-pip python3-setuptools apt-transport-https ca-certificates curl software-properties-common
sudo pip3 install thefuck
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
sudo apt install -y docker-ce

sudo usermod -aG docker ${USER}


cd $WORKSPACE
git clone git@github.com:alesaudate/docker-recipes.git
