#!/bin/bash

if [ $EUID -eq 0 ]; then
	echo "Do not run this script as root. It will ask for credentials when needed."
	exit 1
fi

INITIAL_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
MODULES_DIR=$SCRIPT_DIR/modules

mkdir -p ~/workspace
cd $INITIAL_DIR

cp $SCRIPT_DIR/.bash_aliases ~
source ~/.bash_aliases

mkdir -p $WORKSPACE

if [ ! command -v xclip &> /dev/null ]; then
	sudo apt update
	sudo apt install -y xclip xmllint jq python3-dev python3-pip python3-setuptools apt-transport-https ca-certificates curl software-properties-common
fi

if [ ! command -v fuck &> /dev/null ]; then
	sudo pip3 install thefuck
fi

if [ ! -d "$WORKSPACE/docker-recipes" ]; then
	cd $WORKSPACE
	git clone git@github.com:alesaudate/docker-recipes.git
fi

find $MODULES_DIR -iname "*.load" -exec {} \;

source ~/.bash_aliases

cd $INITIAL_DIR
