#!/bin/bash

script_dir() {
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
}

brew install bash

script_dir
INITIAL_DIR=$SCRIPT_DIR
cp $SCRIPT_DIR/.bash_aliases ~
source ~/.bash_aliases

mkdir -p $WORKSPACE

if ! command -v brew &> /dev/null
then
    echo "Installing brew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if ! command -v docker &> /dev/null
then 
    echo "Installing docker"
    brew cask install docker
fi

if ! command -v gh &> /dev/null
then
    echo "Installing GitHub CLI"
    brew install gh
fi

if [ ! -d $WORKSPACE/docker-recipes ]; then
    cd $WORKSPACE
    gh repo clone alesaudate/docker-recipes
fi

brew install jq
brew install libxml2
brew install xclip

cd $INITIAL_DIR
find ./modules -iname "*.load" -exec {} \;

exec bash -l
